# Generated by Django 5.1.3 on 2024-11-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0036_alter_event_header_image_alter_event_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZammadSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("some_setting", models.CharField(default="A", max_length=10)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretalx_zammad_settings",
                        to="event.event",
                    ),
                ),
            ],
        ),
    ]
